services:
  - type: web
    name: reservation-client
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://reservation-api.onrender.com/api
